### PR TITLE
Only call `connection_lost` after the serial port is actually closed

### LINKED ISSUE #7: Task was destroyed but it is pending!
I've developed a hand full of HA integrations which connect over the serial port. Currently I'm in the process of migration the different libraries used by these integrations from synchronous pyserial to asynchronous communication.

First I migrated to `pyserial-asyncio` and after finding out about `pyserial-asyncio-fast` I used that as a drop in replacement as this seems to be the recommended library to use.

I'm currently working on my [XY Screens projector screen integration](https://github.com/rrooggiieerr/xyscreens.py). When running my unit tests using `pyserial-asyncio` everything goes fine, but when using `pyserial-asyncio-fast` I get the following error:
```
base_events.py:1821 Task was destroyed but it is pending!
task: <Task pending name='Task-52' coro=<SerialTransport._call_connection_lost() done, defined at /Users/rogier/Library/Python/3.12/lib/python/site-packages/serial_asyncio_fast/__init__.py:448> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()]>>
```

The only thing different in the coded is I change `import serial_asyncio` to `import serial_asyncio_fast as serial_asyncio`

### PR DESCRIPTION
**Pull request by puddly**
Supersedes #15 and fixes #7.

I think this is the correct fix for the above problem. pyserial-asyncio called `connection_lost` *before* the serial object was closed. This was a bug.

### CODE REVIEW

**Comment by puddly** [comment]
I'm really not sure what the correct approach here is. Logically, it would make sense that the connection is cleaned up before `connection_lost` is emitted: otherwise, how will a downstream application know when it can re-connect?

On other hand, even the Python stdlib calls `protocol.connection_lost` *before* cleaning up. As do most other [instances online](https://github.com/search?q=call_connection_lost+language%3APython&type=code&l=Python). I think this must be a bug, no?

https://github.com/python/cpython/blob/d005f2c1861dbf0ab3d9f80b54d05d0c0b522c3c/Lib/asyncio/unix_events.py#L824-L831

For example:

```python
import os
import asyncio


class TestProtocol(asyncio.Protocol):
    def __init__(self, pipe):
        self.pipe = pipe

    def connection_made(self, transport):
        print(f"connection_made: {transport!r}")

    def data_received(self, data):
        print(f"data_received: {data!r}")

    def connection_lost(self, exc):
        print(f"connection_lost: {exc!r}")
        assert self.pipe.closed is True  # Fails!


async def main():
    rpipe_fd, wpipe_fd = os.pipe()
    rpipe = os.fdopen(rpipe_fd, 'rb')
    wpipe = os.fdopen(wpipe_fd, 'wb')

    loop = asyncio.get_running_loop()
    reader = asyncio.StreamReader(loop=loop)
    protocol = TestProtocol(rpipe)

    transport, _ = await loop.connect_read_pipe(lambda: protocol, rpipe)

    wpipe.write(b"test")
    await asyncio.sleep(0)

    # Closing the transport
    transport.close()

    # It's not expected for the pipe to immediately close, though it can
    assert rpipe.closed is False

    # The pipe is closed after an event loop iteration
    await asyncio.sleep(0)
    assert rpipe.closed is True


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by puddly** [comment]
I'm testing this change with <https://github.com/zigpy/zigpy/pull/1425>, which affects all zigpy radio libraries and a few other packages.

`universal-silabs-flasher` switches baud rates and rapidly connects/disconnects from the same port when re-probing firmware types and this PR solves a few timing issues that required `await asyncio.sleep(0.5)` to fix.

**Review by bdraco — APPROVED** [review]

**Review by agners — APPROVED** [review]
Awesome find @puddly 

This LGTM, too, it restores behavior as outlined in https://github.com/home-assistant-libs/pyserial-asyncio-fast/issues/7#issuecomment-2226764730. Thanks @cottsay for the analysis!

**Comment by bdraco** [comment]
I’ll do a release in a bit. Sorry I didn’t get it done the other day. Been a bit slammed since the hurricane

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
0.14 published

**Pull request merged**
