### PR TITLE
Prevent tasks from being prematurely garbage collected

### LINKED ISSUE #7: Task was destroyed but it is pending!
I've developed a hand full of HA integrations which connect over the serial port. Currently I'm in the process of migration the different libraries used by these integrations from synchronous pyserial to asynchronous communication.

First I migrated to `pyserial-asyncio` and after finding out about `pyserial-asyncio-fast` I used that as a drop in replacement as this seems to be the recommended library to use.

I'm currently working on my [XY Screens projector screen integration](https://github.com/rrooggiieerr/xyscreens.py). When running my unit tests using `pyserial-asyncio` everything goes fine, but when using `pyserial-asyncio-fast` I get the following error:
```
base_events.py:1821 Task was destroyed but it is pending!
task: <Task pending name='Task-52' coro=<SerialTransport._call_connection_lost() done, defined at /Users/rogier/Library/Python/3.12/lib/python/site-packages/serial_asyncio_fast/__init__.py:448> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()]>>
```

The only thing different in the coded is I change `import serial_asyncio` to `import serial_asyncio_fast as serial_asyncio`

### PR DESCRIPTION
**Pull request by rrooggiieerr**
Fixes https://github.com/home-assistant-libs/pyserial-asyncio-fast/issues/7

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
Thanks @rrooggiieerr

**Comment by bdraco** [comment]
I need to do some updates to the CI and tooling before I can merge this to be able to do a new release

I'll try to get that done today.  I'm traveling today and this weekend so it might have to wait until Monday if I run out of time today

**Comment by bdraco** [comment]
published as 0.12

**Comment by rrooggiieerr** [comment]
Thanks!

**Pull request merged**
